# data
model: ["MOHC-HadGEM2-ES", "MPI-M-MPI-ESM", "NCC-NorESM1-M"]
rcm: ["ICTP-RegCM4-7", "REMO2015"]
scenario: ["rcp26", "rcp85"]
repetitions: 1

# sim pars
warmup: 600
verbose: yes
data_path: "data" # to bind to singularity with `-B`
seed: 42 # for the random selection of years

# singularity
# troll: "https://github.com/sylvainschmitt/singularity-troll/releases/download/0.0.3/sylvainschmitt-singularity-troll.latest.sif"
troll: "singularity/troll.sif"

# tests
test: true
test_years: 0.1
