# data
scenarios: ["RIL1", "RIL2"]
durations: [65]
cycles: 1

# sim pars
historical: [1970, 2005]
spinup: 600
verbose: yes
seed: 42 # for the random selection of years

# singularity
# troll: "https://github.com/sylvainschmitt/singularity-troll/releases/download/0.0.3/sylvainschmitt-singularity-troll.latest.sif"
troll: "singularity/troll.sif"
logginglab: "https://github.com/sylvainschmitt/singularity-LoggingLab/releases/download/0.0.1/LoggingLab.sif"

# tests
test: true
test_years: 0.1
