# plots
area: "French Guiana"
plots: [
   "Piste de Paracou",
   "Réserve naturelle des nouragues",
   ]

# soil
soil_pars: [
  "silt", 
  "clay",
  "sand",
  "soc",
  "bdod",
  "phh2o",
  "cec"
  ]
# silt: proportion of silt
# clay: proportion of clay
# sand: proportion of sand
# soc: soil organic content
# bdod: dry bulk density
# phh20: hydrogen ion activity in water  
# cec: cation exchange capacity at ph 7
depth: [
  "0-5cm"
  ]

# singularity
troll: "https://github.com/sylvainschmitt/singularity-troll/releases/download/0.0.3/sylvainschmitt-singularity-troll.latest.sif"
