# plots
area: "French Guiana"
plots: [
   "Piste de Paracou",
   "Réserve naturelle des nouragues",
   "Saint-Elie, Guyane"
   ]

# soil
soil_pars: [
  "silt", 
  "clay",
  "sand",
  "soc",
  "bdod",
  "phh2o",
  "cec"
  ]
depth: [
  "0-5cm",
  "5-15cm",
  "15-30cm",
  "30-60cm",
  "60-100cm"
  ]

# singularity
troll: "https://github.com/sylvainschmitt/singularity-troll/releases/download/0.0.3/sylvainschmitt-singularity-troll.latest.sif"
