__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  
get_data:
  jobname: "get_data"
  mem: "1G"
  cpus: 1
  time: "01:00:00"

prepare_climate:
  jobname: "prepare_climate"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  
troll:
  jobname: "troll"
  mem: "10G"
  cpus: 1
  time: "96:00:00"
  