__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  partition: "agap_normal"
  
get_soil:
  jobname: "get_soil"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  partition: "agap_normal"

extract_soil:
  jobname: "extract_soil"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  partition: "agap_normal"
  
troll_warm:
  jobname: "troll_warm"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  partition: "agap_normal"
  
gather_warm:
  jobname: "gather_warm"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  partition: "agap_normal"
  