__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  
prepare_guyaflux:
  jobname: "prepare_guyaflux"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

prepare_era:
  jobname: "prepare_era"
  mem: "10G"
  cpus: 10
  time: "01:00:00"

prepare_cordex:
  jobname: "prepare_guyaflux"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  
select_years:
  jobname: "select_years"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

sample_climate:
  jobname: "sample_climate"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

troll_warm:
  jobname: "sample_climate"
  mem: "10G"
  cpus: 1
  time: "96:00:00"
  
troll_exp:
  jobname: "sample_climate"
  mem: "10G"
  cpus: 1
  time: "96:00:00"
  