__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  
spinup_years:
  jobname: "spinup_years"
  mem: "4"
  cpus: 1
  time: "01:00:00"

prepare_spinup:
  jobname: "prepare_spinup"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  
spinup:
  jobname: "spinup"
  mem: "10G"
  cpus: 1
  time: "96:00:00"
  
log:
  jobname: "log"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

postlog:
  jobname: "postlog"
  mem: "10G"
  cpus: 1
  time: "24:00:00"
  
damage:
  jobname: "damage"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

recover:
  jobname: "recover"
  mem: "10G"
  cpus: 1
  time: "96:00:00"
  