__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  partition: "agap_normal"
  
prepare_guyaflux:
  jobname: "prepare_guyaflux"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  partition: "agap_normal"

prepare_era:
  jobname: "prepare_era"
  mem: "10G"
  cpus: 10
  time: "01:00:00"
  partition: "agap_normal"

prepare_cordex:
  jobname: "prepare_guyaflux"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  partition: "agap_normal"
  
select_years:
  jobname: "select_years"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  partition: "agap_normal"

sample_climate:
  jobname: "sample_climate"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  partition: "agap_normal"

troll_warm:
  jobname: "troll_warm"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  partition: "agap_normal"
  
troll_exp:
  jobname: "troll_exp"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  partition: "agap_normal"
  