__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"

sample_coms:
  jobname: "sample_coms"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

spinup:
  jobname: "spinup"
  mem: "10G"
  cpus: 1
  time: "96:00:00"
