__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  
get_soil:
  jobname: "get_soil"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

extract_soil:
  jobname: "extract_soil"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

troll_warm:
  jobname: "troll_warm"
  mem: "10G"
  cpus: 1
  time: "96:00:00"

gather_warm.R:
  jobname: "gather_warm.R"
  mem: "100G"
  cpus: 1
  time: "01:00:00"
  